#!/bin/bash
# Epic 3 Manual Testing Guide
# Run test cases via Agentverse chat interface or ASI:One

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          Epic 3 Manual Testing - Test Cases                ║"
echo "╔════════════════════════════════════════════════════════════╗"
echo ""
echo "📋 Instructions:"
echo "1. Open https://agentverse.ai/ and sign in"
echo "2. Navigate to coordinator agent or use chat interface"
echo "3. Send each test case message below"
echo "4. Monitor logs: tail -f /tmp/*_mailbox.log"
echo "5. Verify expected results match actual output"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ TEST CASE 1: Meningitis Emergency (ALREADY PASSED ✅)"
echo "Status: COMPLETED on Day 4"
echo "Result: 5 symptoms extracted, red flags detected, emergency classification"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🧪 TEST CASE 2: Pneumonia - Urgent Scenario"
echo "Input:"
echo "  \"I've had a bad cough for 5 days, fever around 102°F,"
echo "   and difficulty breathing. I'm 45 years old.\""
echo ""
echo "Expected Results:"
echo "  - Urgency: URGENT"
echo "  - Differential: Pneumonia, COVID-19, Bronchitis"
echo "  - Treatment: Antibiotics (amoxicillin), rest, hydration"
echo "  - Specialist: Pulmonologist or Primary Care"
echo "  - Follow-up: Within 24 hours"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🧪 TEST CASE 3: Common Cold - Routine Scenario"
echo "Input:"
echo "  \"I have a runny nose, mild sore throat, and feel a bit tired."
echo "   Started yesterday. I'm 30 years old.\""
echo ""
echo "Expected Results:"
echo "  - Urgency: ROUTINE"
echo "  - Differential: Common cold, early flu, allergies"
echo "  - Treatment: Rest, fluids, OTC pain relievers"
echo "  - Follow-up: 1-2 weeks (or if symptoms worsen)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🧪 TEST CASE 4: Allergy Contraindication Detection"
echo "Input:"
echo "  \"I have a bad cough and chest pain. I'm allergic to penicillin."
echo "   I'm 50 years old.\""
echo ""
echo "Expected Results:"
echo "  - ⚠️ Allergy warning displayed for penicillin"
echo "  - Alternative antibiotics suggested (azithromycin, fluoroquinolones)"
echo "  - No penicillin-based treatments recommended"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🧪 TEST CASE 5: Multi-Symptom Differential Diagnosis"
echo "Input:"
echo "  \"I have a headache, nausea, and fatigue."
echo "   It's been going on for 3 days. I'm 35 years old.\""
echo ""
echo "Expected Results:"
echo "  - Multiple diagnoses (2-5): Migraine, Tension headache, Influenza, Gastroenteritis"
echo "  - Confidence scores shown for each"
echo "  - Appropriate uncertainty handling"
echo "  - Reasoning for each diagnosis"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🧪 TEST CASE 6: Elderly Age Adjustment"
echo "Input:"
echo "  \"I have chest pain and shortness of breath. I'm 72 years old.\""
echo ""
echo "Expected Results:"
echo "  - Urgency: EMERGENCY (age-appropriate escalation)"
echo "  - Red flag: Chest pain (cardiac emergency)"
echo "  - Differential: Heart attack, angina, pulmonary embolism"
echo "  - Age-over-65 cautions displayed"
echo "  - Dose adjustment warnings"
echo "  - Immediate ER recommendation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Pass Criteria (ALL test cases):"
echo "  ✅ Complete without errors"
echo "  ✅ Generate full diagnostic report"
echo "  ✅ Display reasoning chains"
echo "  ✅ Include medical disclaimers"
echo "  ✅ Show evidence sources"
echo "  ✅ Detect red flags (where applicable)"
echo "  ✅ Check contraindications (where applicable)"
echo "  ✅ Recommend appropriate specialist"
echo "  ✅ Response time <10 seconds"
echo ""
echo "╚════════════════════════════════════════════════════════════╝"
